/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package smm.project.pkg7;

import sm.rlm.iu.Lienzo2D;

/**
 *
 * @author rober
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private String formatoInicial;
    private VentanaPrincipal vp;
    
    /**
     * Creates new form VentanaInterna
     *
     * @param vp
     */
    public VentanaInterna(VentanaPrincipal vp) {
        initComponents();
        
        this.vp = vp;
    }
    
    public Lienzo2D getLienzo2D() {
        return this.lienzo2D1;
    }

    public String getFormatoInicial() {
        return (formatoInicial == null) ? "jpg" : formatoInicial;
    }

    public void setFormatoInicial(String formatoInicial) {
        this.formatoInicial = formatoInicial;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D1 = new sm.rlm.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lienzo2D1.setBackground(new java.awt.Color(255, 255, 255));
        lienzo2D1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2D1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2D1Layout = new javax.swing.GroupLayout(lienzo2D1);
        lienzo2D1.setLayout(lienzo2D1Layout);
        lienzo2D1Layout.setHorizontalGroup(
            lienzo2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        lienzo2D1Layout.setVerticalGroup(
            lienzo2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzo2D1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2D1MouseMoved
        if (vp != null) {
            vp.actualizarCoordenadas(evt.getX(), evt.getY());
            vp.actualizarRgb(this.lienzo2D1.getR(), this.lienzo2D1.getG(), this.lienzo2D1.getB());
        }
    }//GEN-LAST:event_lienzo2D1MouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.rlm.iu.Lienzo2D lienzo2D1;
    // End of variables declaration//GEN-END:variables
}
